# Generated by Django 2.2 on 2020-08-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='type',
        ),
        migrations.CreateModel(
            name='GoalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_tags', to='webapp.Goal', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_goals', to='webapp.Type', verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='goals', through='webapp.GoalType', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
