# Generated by Django 2.2 on 2020-08-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200809_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='type',
            new_name='type_old',
        ),
    ]
