# Generated by Django 2.2 on 2020-08-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200809_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='goals', to='webapp.Type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='type_old',
            field=models.ManyToManyField(blank=True, related_name='goal_set', through='webapp.GoalType', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
