# Generated by Django 2.2 on 2020-08-09 08:40

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Goal = apps.get_model('webapp.Goal')
    for goal in Goal.objects.all():
        goal.type.set(goal.type_old.all())


def rollback_transfer(apps, schema_editor):
    Goal = apps.get_model('webapp.Goal')
    for goal in Goal.objects.all():
        goal.type_old.set(goal.type.all())


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0004_auto_20200809_1438'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
