# Generated by Django 2.2 on 2020-08-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200809_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='type_old',
        ),
        migrations.DeleteModel(
            name='GoalType',
        ),
    ]
