# Generated by Django 2.2 on 2020-08-13 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200813_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='summary',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Заголовок'),
        ),
    ]
