# Generated by Django 2.2 on 2020-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_goal_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
