# Generated by Django 2.2 on 2020-08-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200821_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='webapp.Project', verbose_name='Проект'),
        ),
    ]
