# Generated by Django 2.2 on 2020-08-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200822_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='webapp.Project', verbose_name='Проект'),
        ),
    ]
